# Generated by Django 4.2.4 on 2024-02-06 18:29

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
